#!/bin/sh
### BEGIN INIT INFO
# Provides:          tomcat
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Create dynamic part of TomCat9
# Description:
### END INIT INFO

do_start () {
        /opt/tomcat9/bin/startup.sh
}

do_status () {
        netstat -lnp | grep 8080 2>&1 > /dev/null
        if [ $? = 0 ]; then
                echo "Servico iniciado"
        else
                echo "Servico nao iniciado"
        fi
}

do_stop () {
        /opt/tomcat9/bin/shutdown.sh
}




case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        do_stop
        do_start
        ;;
  stop)
	do_stop
        ;;
  status)
        do_status
        exit $?
        ;;
  *)
        echo "Usage: motd [start|restart|stop|status]" >&2
        exit 3
        ;;
esac

